### PR TITLE
Fix badge/counter icon not being removed correctly (fixes #1251)

### LINKED ISSUE #1251: Badge does not get removed using the counter option
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

The badge counter does not clear when the number is removed from the apps title. e.g. `Home / Twitter (2)` -> `Home / Twitter` means the badge icon remains. The only way to reset it is to close and re-open the app. 

I've also noticed the same behaviour with messenger.com

I can test on a macOS 11.4 machine tomorrow to exclude the fact I'm on 11.5 beta. 

**Steps to reproduce**

```
nativefier https://twitter.com -f -i icon.icns -n Twitter --counter --bounce --darwin-dark-mode-support --inject styles.css --title-bar-style "hidden" --single-instance
```

- Install above
- Receive a message/notification
- View notification which clears the count in the title
- Observe the badge persisting

Alternatively, you can fake it with dev tools...

- Edit the title in dev tools to `Home / Twitter (1)` 
- Observe the icon badge showing (1) 
- Edit the title to remove the `(1)` 
- Observe the badge persisting 

**Expected behavior**

When the title changes to remove the numeric value, the badge clears from the icon. 

**Actual behavior**

When the title changes to remove the numeric value, the badge remains. 

**Debug info**

CleanShot 2021-07-04 at 18 42 54@2x

CleanShot 2021-07-04 at 18 43 16@2x

**Context**

 - Nativefier: 44.0.6
 - Node.js: 16.1.0
 - Npm: 7.11.2
 - OS: macOS 11.5 Beta (20G5052c) 
 - Is it a regression? Unsure, I've only just moved to Nativefier from Unite & Flotato.

### PR DESCRIPTION
**Pull request by sampotts**
The current check for `count` means the value to reset/remove the badge (`''`) is treated as `false` and therefore the badge does not get removed. This PR changes the check for `undefined` instead which resolves the issue. 

Related issue: 
https://github.com/nativefier/nativefier/issues/1251

Testing performed:
- I ran `npm t` as per the docs. All tests passed. 
- I created a new app build for Twitter (`https://twitter.com`) and Messenger (`https://messenger.com`) to verify the correct behaviour. Both were showed the issue as resolved.

### CODE REVIEW

File: app/src/main.ts [hunk 1]
```diff
@@ -169,7 +169,7 @@ if (appArgs.lang) {
 let currentBadgeCount = 0;
 const setDockBadge = isOSX()
   ? (count?: number | string, bounce = false): void => {
-      if (count) {
+      if (typeof count !== 'undefined') {
```
Comment (ronjouch) [inline app/src/main.ts:172]: This works, but out of curiosity: any reason to not simply

```suggestion
      if (count !== undefined) {
```

**Review by ronjouch — APPROVED** [review]
Thanks! One question.

File: app/src/main.ts (hunk 1 above)
Comment (sampotts) [reply app/src/main.ts]: Good point. Given it's a function argument, it makes sense.

**Comment by ronjouch** [comment]
Thx, merged 🙂. Will cut a release soon-ish.

**Comment by ronjouch** [comment]
Released in [44.0.7](https://github.com/nativefier/nativefier/releases/tag/v44.0.7).

**Comment by sampotts** [comment]
Awesome, thanks!
