### PR TITLE
macOS: Fix crash when using --tray (fix #527), and invisible icon (fix #942, fix #668)

### LINKED ISSUE #527: --tray flag causes icon-related startup crash
### Description

When I start an app created with nativefier, I always get the following error:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /home/alem0lars/trello-linux-x64/resources/app/icon.png
    at createTrayIcon (/home/alem0lars/trello-linux-x64/resources/app/lib/webpack:/app/src/components/trayIcon/trayIcon.js:18:21)
    at App.<anonymous> (/home/alem0lars/trello-linux-x64/resources/app/lib/webpack:/app/src/main.js:107:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

### Steps to reproduce issue

Create app:

```
nativefier -p linux -n trello --disable-dev-tools --tray --single-instance --disable-gpu-sandbox --zoom 0.7 https://trello.com
```

Then run it:

```
./trello-linux-x64/trello
```

### LINKED ISSUE #668: Tray icon not displayed on macOS
### Description

Thanks for nativefier, it's very useful.

The tray icon on mac os is not displayed.

image

image

### Details

- nativefying the asana website.
- `nativefier https://app.asana.com` ; I've also tried `nativefier https://app.asana.com --icon ~/Downloads/asana.icns --tray` ; it makes no difference.
- Nativefier: `7.6.7`
- node.js: `v8.11.3`
- OS: `macOS High Sierra 10.13.6`

### LINKED ISSUE #942: Tray icon is blank on macOS
When having an app open, it adds an invisible icon item to the OS top bar.

1. There should be a parameter to change that to an actual icon
2. There should be a parameter to remove it completely.

Example 1:
Untitled

Example 2: [View GIF](https://share.getcloudapp.com/geu2ng77)

### PR DESCRIPTION
**Pull request by fabiwlf**
This PR is meant to fix a startup crash on macOS when using the --tray cli option, it's mentioned in #527.

image
 
It will also accomplish to correctly display the tray icon on macOS, which would close #942 and #668.  

image

Example:

`
nativefier "web.whatsapp.com" --tray
`

### CODE REVIEW

**Review by fabiwlf — COMMENTED** [review]
Fixed CI

File: icon-scripts/convertToTrayIcon [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+NAME=$(basename "${SOURCE}")
+EXT="${NAME##*.}"
+
+if [ "${EXT}" == "png" ]; then
+    cp "${SOURCE}" "${DEST}"
+    exit 0
+fi
+
+sips --setProperty format png --resampleHeightWidth "256" "256" "${SOURCE}" --out "${DEST}"
```
Comment (TheCleric) [inline icon-scripts/convertToTrayIcon:32]: Is `sips` a default install on Mac OS?

File: src/build/buildIcon.ts [hunk 2]
```diff
@@ -83,12 +83,16 @@ export function convertIconIfNecessary(options: AppOptions): void {
...
   try {
-    const iconPath = convertToIcns(options.packager.icon);
-    options.packager.icon = iconPath;
-    return;
+    if (!iconIsIcns(options.packager.icon)) {
+      const iconPath = convertToIcns(options.packager.icon);
+      options.packager.icon = iconPath;
+    }
+    if (options.nativefier.tray) {
+      convertToTrayIcon(options.packager.icon);
```
Comment (TheCleric) [inline src/build/buildIcon.ts:91]: My only concern here is for the following scenario:

- Building a mac app
- With a tray icon
- On a non-Mac build machine
- (And may even be passing a `.icns` file to avoid errors)

Will now cause a recoverable error and no icon (which seems like it was the behavior before anyway). Since there is no degradation in functionality, this is fine, but I think we should probably update the `--tray` entry of `api.md` to document this known limitation.

File: src/build/buildIcon.ts [hunk 3]
```diff
@@ -83,12 +83,16 @@ export function convertIconIfNecessary(options: AppOptions): void {
...
+    }
   } catch (error) {
     log.warn('Failed to convert icon to .icns, skipping.', error);
     options.packager.icon = undefined;
-    return;
   }
+  return;
```
Comment (TheCleric) [inline src/build/buildIcon.ts:97]: With this function being void, I don't think you actually need a return here.

File: src/build/buildNativefierApp.ts [hunk 4]
```diff
@@ -65,7 +65,18 @@ async function copyIconsIfNecessary(
     options.packager.platform === 'darwin' ||
     options.packager.platform === 'mas'
   ) {
-    log.debug('No copying necessary on macOS; aborting');
+    if (options.nativefier.tray) {
+      //tray icon needs to be .png
+      log.debug('Copying icon for tray application');
+      const trayIconFileName = `icon.png`;
```
Comment (TheCleric) [inline src/build/buildNativefierApp.ts:71]: I think we should probably pick a different filename here as this could conflict with a linux icon file.

**Review by TheCleric — CHANGES_REQUESTED** [review]

File: icon-scripts/convertToTrayIcon (hunk 1 above)
Comment (fabiwlf) [reply icon-scripts/convertToTrayIcon:32]: Yes it is

File: src/build/buildNativefierApp.ts (hunk 4 above)
Comment (fabiwlf) [reply src/build/buildNativefierApp.ts:71]: What about tray-icon?

File: src/build/buildIcon.ts (hunk 3 above)
Comment (fabiwlf) [reply src/build/buildIcon.ts:97]: yup

File: src/build/buildIcon.ts (hunk 2 above)
Comment (fabiwlf) [reply src/build/buildIcon.ts:91]: Oh didn't think about that. So yeah, thats not possible.

File: src/build/buildNativefierApp.ts (hunk 4 above)
Comment (TheCleric) [reply src/build/buildNativefierApp.ts:71]: Works for me.

**Review by fabiwlf — COMMENTED** [review]
☑️ Requested changes

**Comment by TheCleric** [comment]
@fabiwlf can we update the `api.md` to document this new limitation of the `--tray` parameter?

File: docs/api.md [hunk 5]
```diff
@@ -620,6 +620,8 @@ Application will stay as an icon in the system tray. Prevents application from b
 
 When the optional argument `start-in-tray` is provided, i.e. the application is started using `--tray start-in-tray`, the main window will not be shown on first start.
 
+Note: When creating a macOS application with the --tray option on a non macOS host machine, the tray icon will not be visible in the menu bar.
```
Comment (ronjouch) [inline docs/api.md:623]:
```suggestion
Limitation: when creating a macOS app using option `--tray`, from a non-macOS build machine, the tray icon (in the menu bar) will be invisible.
```

**Review by ronjouch — APPROVED** [review]
Awesome! Thanks everybody! Merging.
