### PR TITLE
macOS: fix Open In New Tab (fix #1260)

### LINKED ISSUE #1260: v45.0.0 in macOS 10.15.x breaks new windows/tab functions
**Homework**

- [x ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ x] I searched existing issues, open & closed. Yes, my bug is new.
- [ x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

v45.0.0 in macOS 10.15.x breaks new tab in windows functions. Using Quip, when I press the "+" button to create a new tab, the window vs tab becomes broken /confusing. The functionality of a single window with multiple tabs no longer works, and spins up additional windows that show as a tab in the main window.

**Steps to reproduce**

```
nativefier -i ./quip.png --name "Quip" --darwin-dark-mode-support --single-instance -f -m --internal-urls "(.*?)" "https://quip.com/"
```

**Expected behavior**

Creating a new tab, only creates 1 additional tab in the existing window. 

**Actual behavior**

Each time a tab is created, 2 tabs are actually created as well as an additional window is created in the background that is linked to one of the tabs. Closing one of the background windows closes all of the windows.

Screen Shot 2021-07-20 at 10 04 53 AM

* macOS 10.15.7
* `npm outdated -g --depth=0 nativefier` show no outdated tools.
```

nativefier@45.0.0 | MIT | deps: 11 | versions: 105
Wrap web apps natively
https://github.com/nativefier/nativefier

keywords: desktop, electron, app, native, wrapper

bin: nativefier

dist
.tarball: https://registry.npmjs.org/nativefier/-/nativefier-45.0.0.tgz
.shasum: 4dc750d478078d8c8cbdafe1a2273911cea69c8d
.integrity: sha512-StUxs2XrE5Xh1jhikP3979OtNFpIiEOf3GnKMXzvzxgIqmgTPzDeyjWlzCoO+Xxqg8fxqfumLNwgYGx7gVDqQw==
.unpackedSize: 1.1 MB

dependencies:
axios: ^0.21.1              electron-packager: ^15.2.0  gitcloud: ^0.2.3            hasbin: ^1.2.3              loglevel: ^1.7.1            ncp: ^2.0.0                 page-icon: ^0.4.0           sanitize-filename: ^1.6.3   source-map-support: ^0.5.19 tmp: ^0.2.1                 yargs: ^17.0.1

dist-tags:
latest: 45.0.0
```

### PR DESCRIPTION
**Pull request by TheCleric**
Hi @ronjouch , long time no talk!

Should fix #1260

### CODE REVIEW

File: app/src/components/contextMenu.ts [hunk 1]
```diff
@@ -43,12 +47,21 @@ export function initContextMenu(
...
-              createNewTab(
-                outputOptionsToWindowOptions(options),
-                setupNativefierWindow,
+              // Fire a new window event for a foreground tab
+              (window as BrowserWindow).webContents.emit(
+                // event name
+                'new-window',
+                // event object
+                {
+                  newGuest: undefined,
```
Comment (ronjouch) [inline app/src/components/contextMenu.ts:56]: A lil' comment might be halpful to sum up that thing is

**Review by ronjouch — APPROVED** [review]
Wheeeeeeeee

File: app/src/components/contextMenu.ts (hunk 1 above)
Comment (TheCleric) [reply app/src/components/contextMenu.ts:60]: @ronjouch Done!
