### PR TITLE
Fix Widevine by properly listening to widevine-... events, and update docs (fix #1153)

### LINKED ISSUE #1147: Until signing the Nativefier app with CastLabs sign-pkg, Udemy videos fail to load even with flag --widevine, with error "Widevine license acquisition failed >> Verified media path has been tampered"
### Problem 

Hello, I recently used nativefier to have a local Desktop app for watching Udemy courses. For some courses that I try to watch from the app, I am getting a **Video Error**. For other courses, I am able to watch the video playback without any problems. I was thinking it might be an issue from Udemy, but I went to Udemy on the browser to see if I can watch videos for the courses that have issues. It turns out the playback works perfectly on the browser. 

Any ideas on how this can be fixed? 

#### Nativefier Version 

Screen Shot 2021-04-01 at 4 27 25 PM

#### Web Browser Version

Screen Shot 2021-04-01 at 4 27 55 PM

### LINKED ISSUE #1153: Nativfier issue with HBO Max
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Attempting to play anything from HBO Max when built with nativfier displays error.

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```js
nativefier --name "HBO Max" "https://play.hbomax.com/" --flash --tray --conceal --widevine --enable-es3-apis --internal-urls ".*?" --background-color "#333333" --icon "C:\Native Apps\bin\resources\ico\HBO Max.ico" --verbose

Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

ATTENTION: Using the **unofficial** Electron from castLabs
It implements Google's Widevine Content Decryption Module (CDM) for DRM-enabled playback.
Simply abort & re-run without passing the widevine flag to default to 11.1.1

Performing async options post-processing.
Inferring user agent for electron 11.1.1-wvvmp / win32
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Got icon from options. Using it, no inferring needed
Got name HBO Max from options. No inferring needed
Sanitized filename for HBO Max : HBO Max
Unable to infer chrome version for user agent, using 87.0.4280.88
Given chrome 87.0.4280.88 on win32, using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

Preparing Electron app...
Copying electron app from C:\Users\Owner\AppData\Roaming\npm\node_modules\nativefier\app to C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5
Writing app config to C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5\nativefier.json
No files to inject, skipping copy.
Updating C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5\package.json 'name' field to hbo-max-nativefier-7b319c

Converting icons...
Building for Windows and icon is already a .ico, no conversion needed
Copying icons if necessary
Copying icon C:\Native Apps\bin\resources\ico\HBO Max.ico to C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5\icon.ico

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v15.6.0
  electron-packager Host Operating system: win32 10.0.19043 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":true,"darwinDarkModeSupport":false,"dir":"C:\\Users\\Owner\\AppData\\Local\\Temp\\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5","electronVersion":"11.1.1-wvvmp","icon":"C:\\Native Apps\\bin\\resources\\ico\\HBO Max.ico","name":"HBO Max","out":"C:\\Native Apps\\bin\\apps\\Entertainment","overwrite":true,"platform":"win32","targetUrl":"https://play.hbomax.com/","tmpdir":false,"win32metadata":{"ProductName":"HBO Max","InternalName":"HBO Max","FileDescription":"HBO Max"}} +1ms
  electron-packager Target Platforms: win32 +3ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Requiring author in package.json, as CompanyName was not specified for win32metadata +0ms
  electron-packager Inferring appVersion from version in C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5\package.json +8ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\Owner\AppData\Local\Temp\nativefier-4-7-24-app--9604-z2jHJHnT6Jw5\package.json +1ms
  electron-packager Application name: HBO Max +13ms
  electron-packager Target Electron version: 11.1.1-wvvmp +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"11.1.1-wvvmp","artifactName":"electron"} +0ms
Packaging app for platform win32 x64 using electron v11.1.1-wvvmp
  electron-packager Creating C:\Native Apps\bin\apps\Entertainment\win32-x64-template +10ms
  electron-packager Extracting C:\Users\Owner\AppData\Local\electron\Cache\httpsgithub.comcastlabselectron-releasesreleasesdownloadv11.1.1-wvvmpelectron-v11.1.1-wvvmp-win32-x64.zip\electron-v11.1.1-wvvmp-win32-x64.zip to C:\Native Apps\bin\apps\Entertainment\win32-x64-template +2ms
  electron-packager Initializing app in C:\Native Apps\bin\apps\Entertainment\HBO Max-win32-x64 from C:\Native Apps\bin\apps\Entertainment\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-darwin-x64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-darwin-arm64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-linux-ia32',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-linux-x64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-linux-armv7l',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-linux-arm64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-linux-mips64el',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-mas-x64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-mas-arm64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-win32-ia32',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-win32-x64',
  'C:\\Native Apps\\bin\\apps\\Entertainment\\HBO Max-win32-arm64'
] +4s
  electron-packager Running asar with the options {} +639ms
  electron-packager Renaming electron.exe to HBO Max.exe in C:\Native Apps\bin\apps\Entertainment\HBO Max-win32-x64 +91ms
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"HBO Max","InternalName":"HBO Max","OriginalFilename":"HBO Max.exe","ProductName":"HBO Max","CompanyName":"Jia Hao"},"file-version":"1.0.0","product-version":"1.0.0","icon":"C:\\Native Apps\\bin\\resources\\ico\\HBO Max.ico"} +0ms

Finalizing build...
App built to C:\Native Apps\bin\apps\Entertainment\HBO Max-win32-x64 , move it wherever it makes sense for you and run the contained .exe file.
```

**Expected behavior**

It should play the video.

**Actual behavior**

Fails and displays the following error message:

 ```cs
 Cannot play ttile
 Please make sure your browser is not in private mode.
 ```

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: 42.2.0
 - Node.js: 15.6.0
 - Npm: 7.4.0
 - OS: Windows 10 build 21H1
 - Is it a regression? No
 - Additional context: HBO Max uses widevine, however it seems to have the widevine plugin simply isn't working with it...

### PR DESCRIPTION
**Pull request by TheCleric**
As documented in #1153, for Widevine support to work properly, we need to listen for the Widevine ready event, and as well for certain sites the app must be signed.

This PR adds the events, and as well adds better documentation on the signing limitation.

This may also help resolve #1147

### CODE REVIEW

**Comment by ronjouch** [comment]
@TheCleric I merge your doc with mine added minutes ago before I saw this PR.

File: .gitignore [hunk 1]
```diff
@@ -43,6 +43,8 @@ build/Release
 # Dependency directory
 # https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git
 node_modules
+# Python virtual environment in case it's created for the Castlabs code signing tool
+venv
```
Comment (ronjouch) [inline .gitignore:47]: :ok_hand:

File: app/src/main.ts [hunk 2]
```diff
@@ -179,83 +179,107 @@ if (shouldQuit) {
...
-
-    // Register global shortcuts
-    if (appArgs.globalShortcuts) {
-      appArgs.globalShortcuts.forEach((shortcut) => {
-        globalShortcut.register(shortcut.key, () => {
-          shortcut.inputEvents.forEach((inputEvent) => {
-            mainWindow.webContents.sendInputEvent(inputEvent);
-          });
+  if (appArgs.widevine !== undefined) {
+    // @ts-ignore
```
Comment (ronjouch) [inline app/src/main.ts:183]: Here and below: I like to comment why `@ts-ignore` is used when it is. Pls inline comment each of these. TSC is fine with it. For example,

```suggestion
    // @ts-ignore because blah blah blah. Alternative is to foo, but we prefer bar.
```

File: app/src/main.ts [hunk 3]
```diff
@@ -179,83 +179,107 @@ if (shouldQuit) {
...
+    });
+  } else {
+    app.on('ready', () => {
+      console.log('ready');
+      ready();
+    });
+  }
+}
+
+function ready(): void {
```
Comment (ronjouch) [inline app/src/main.ts:208]:
```suggestion
function onReady(): void {
```

for consistency with our other similar event handlers?

**Review by ronjouch — APPROVED** [review]
@TheCleric two micro-nits, then feel free to merge
