### PR TITLE
Fix injecting multiple css/js files (fix #458)

### LINKED ISSUE #458: --injecting multiple js files mangles them in nativefied app
## Description

When injecting multiple files, the final rendering of the inject.js file is corrupted

#### test1.js
```javascript
alert('Test1')
```

#### test2.js
```javascript
console.log('Test2')
```

#### Run
```shell
nativefier --inject test1.js --inject test2.js --name Github https://github.com
```

####  Github.app/Contents/Resources/app/inject/inject.js
```javascript
alert('Test1')
st2')
```

## Specifications

Version of Nativefier (run `nativefier --version`): `v7.4.1`
Version of Node.js (run `node --version`): `v8.5.0`
OS: `macOS High Sierra 10.13.1`

### PR DESCRIPTION
**Pull request by TheCleric**
Fixes #458

### CODE REVIEW

File: src/build/prepareElectronApp.ts [hunk 1]
```diff
@@ -92,33 +94,37 @@ async function maybeCopyScripts(srcs: string[], dest: string): Promise<void> {
...
+  // use a simple random string to prevent collision
+  const postFixHash = generatePostFixHash(url);
   const normalized = appName
     .toLowerCase()
     .replace(/[,:.]/g, '')
     .replace(/[\s_]/g, '-');
   return `${normalized}-nativefier-${postFixHash}`;
 }
 
+function generatePostFixHash(seed: string, length = 6): string {
```
Comment (ronjouch) [inline src/build/prepareElectronApp.ts:120]: Three things:

1. Function is a bit weirdly named, it's more `generateRandomPostfix` than a hash.
2. Also, it's absolutely not a big deal here (we don't need strong crypto here), but there's no point using weak `Math.random()`, when we have good RNG APIs in Node. Please replace the Math.random call with a call to https://nodejs.org/docs/latest-v10.x/api/crypto.html#crypto_crypto_randombytes_size_callback or similar
4. Also, since we're doing random anyway, why bother with a seed param? Why not seed with just the call to Crypto.randomSomething ?

**Comment by TheCleric** [comment]
@ronjouch take a look and make sure I addressed your concerns please.

File: docs/api.md [hunk 2]
```diff
@@ -514,7 +514,7 @@ Forces the maximum disk space to be used by the disk cache. Value is given in by
 --inject <value>
 ```
 
-Allows you to inject a javascript or css file. This command can be run multiple times to inject the files.
+Allows you to inject javascript or css files. This command can be run multiple times to inject multiple files.
```
Comment (ronjouch) [inline docs/api.md:517]: Little clarif by the way:

```suggestion
Allows you to inject javascript or css files. This command can be repeated multiple times to inject multiple files.
```

File: src/build/prepareElectronApp.ts [hunk 3]
```diff
@@ -111,41 +112,33 @@ async function maybeCopyScripts(srcs: string[], dest: string): Promise<void> {
...
   }
 }
 
-function normalizeAppName(appName: string, url: string): string {
-  // use a simple 3 byte random string to prevent collision
-  const hash = crypto.createHash('md5');
-  hash.update(url);
-  const postFixHash = hash.digest('hex').substring(0, 6);
+function normalizeAppName(appName: string): string {
+  // use a simple random string to prevent collision
```
Comment (ronjouch) [inline src/build/prepareElectronApp.ts:129]:
```suggestion
  // use a simple random string to prevent collisions
```

File: src/build/prepareElectronApp.ts [hunk 4]
```diff
@@ -111,41 +112,33 @@ async function maybeCopyScripts(srcs: string[], dest: string): Promise<void> {
...
+  const postFixHash = generateRandomSuffix();
```
Comment (ronjouch) [inline src/build/prepareElectronApp.ts:130]: By the way, I see you commented on an issue about this hash/suffix. This is related to https://github.com/nativefier/nativefier/pull/888 . Is the reason for this hash clear to you, and do you think we should keep doing it?

File: src/helpers/helpers.test.ts [hunk 5]
```diff
@@ -34,3 +34,25 @@ describe('isArgFormatInvalid', () => {
     expect(isArgFormatInvalid('--test-run-with-many-dashes')).toBe(false);
   });
 });
+
+describe('generateRandomSuffix', () => {
```
Comment (ronjouch) [inline src/helpers/helpers.test.ts:38]: 👍

**Review by ronjouch — APPROVED** [review]
A few questions, and nits that I'll apply directly. I merged master, too.

If the questions are clear / unproblematic to you, 👍 to merge.

File: src/build/prepareElectronApp.ts (hunk 4 above)
Comment (TheCleric) [reply src/build/prepareElectronApp.ts:130]: It is clear to me, and I do think we should keep doing it. I do not see the harm in it as long as we reference the app name correctly (i.e., user provided/inferred) where appropriate instead of this internal one.
