### PR TITLE
Fixes ignored --file-download-options

### LINKED ISSUE #1275: -file-download-options '{\"saveAs\": true}' is being ignored
**Bug description**

`-file-download-options "{\"saveAs\": true}"` is being ignored. 

**Expected behavior**: click on a link to download a file and the "Save As" dialog appears.

**Actual behavior**: nothing appears to happen and the downloaded files appears in the Downloads folder.

```
nativefier https://www.fastmail.com/ --name FastMail --internal-urls ".*?fastmail.*?" --file-download-options "{\"saveAs\": true}" --disable-dev-tools --disk-cache-size 0 --icon email-envelope-icon.ico --inject spell.js
```

**Verbose Log**
[nosaveasnativefierlog.txt](https://github.com/nativefier/nativefier/files/7078617/nosaveasnativefierlog.txt)

**Context**

 - Nativefier: 45.0.0
 - Node.js: 15.9.0
 - Npm: 7.21.0
 - OS: Windows 10 Pro build 19042
 - Is it a regression? YES - last working: 44.0.7 / first broken version: 45.0.0

### PR DESCRIPTION
**Pull request by abhi12299**
This fixes #1275 by assigning camel cased options in parsed arguments in the `parseArgs` function.

### CODE REVIEW

**Comment by abhi12299** [comment]
@TheCleric please review this and let me know if there are any changes.

File: src/cli.ts [hunk 1]
```diff
@@ -582,6 +583,8 @@ export function parseArgs(args: yargs.Argv<RawOptions>): RawOptions {
   ]) {
     if (parsed[arg] && typeof parsed[arg] === 'string') {
       parsed[arg] = parseJson(parsed[arg] as string);
+      // also set camel-cased option keys
```
Comment (ronjouch) [inline src/cli.ts:586]: Pls replace with a comment that says _why_, not just _what_. The _what_ is the code, and in such a case the code is sufficiently simple to not need a translation to English, but a _why_ giving context will be appreciated by our future selves or other maintainers wondering why we do this 🙂.

**Review by ronjouch — COMMENTED** [review]
Thanks! Just one nit about a comment.

File: src/cli.ts (hunk 1 above)
Comment (abhi12299) [reply src/cli.ts]: Please check the latest commit. Have explained a bit more now.

**Comment by ronjouch** [comment]
@abhi12299 thanks! Merged, will ship in the next release, which I'll release in a couple days/weeks.

**Comment by xuejinpeng** [comment]
Now there is a new problem. When opening a new window to save the downloaded file through window.open, the window will not be automatically closed after selecting the save path.

**Comment by abhi12299** [comment]
> Now there is a new problem. When opening a new window to save the downloaded file through window.open, the window will not be automatically closed after selecting the save path.

Can you provide a minimal example?
