### PR TITLE
macOS: Prompt for accessibility permissions if needed by Global Shortcuts using Media Keys (fix #1120)

### LINKED ISSUE #1120: Setting a media key as a global shortcut in Mac OS 10.14+ do not work
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When setting a media key (MediaPlayPause, MediaNextTrack, MediaPreviousTrack, MediaStop) on an app in MacOS, the shortcuts do not work.

**Steps to reproduce**

`nativefier --verbose --global-shortcuts nativefier-media-keys.json -n "Pandora" https://www.pandora.com`

```
nativefier --verbose --global-shortcuts nativefier-media-keys.json -n "Pandora" https://www.pandora.com
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Use global shortcuts file at /Users/TheCleric/Downloads/nativefier-media-keys.json

Performing async options post-processing.
Inferring user agent for electron 11.3.0 / darwin
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://www.pandora.com/ on darwin
Inferring icon from store for https://www.pandora.com/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Got name Pandora from options. No inferring needed
Sanitized filename for Pandora : Pandora
Got 249 icons from gitcloud
Max icon match score: 1
Downloading https://nativefier.github.io/nativefier-icons/files/pandora.png
Got an icon from the page.
Writing 51.1 kb icon to /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconinfer--26188-2H8dD19rVveH/icon.png
Associated electron v11.3.0 to chrome v87.0.4280.141
Given chrome 87.0.4280.141 on darwin, using user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Preparing Electron app...
Copying electron app from /Users/TheCleric/Dev/nativefier/app to /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-app--26188-eD8hoeUp2kKQ
Writing app config to /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-app--26188-eD8hoeUp2kKQ/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-app--26188-eD8hoeUp2kKQ/package.json 'name' field to pandora-nativefier-ceb3d0

Converting icons...
Converting icon /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconinfer--26188-2H8dD19rVveH/icon.png to /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconconv--26188-lbKOjKK53S7Y/icon.icns. Calling shell command: "/Users/TheCleric/Dev/nativefier/icon-scripts/convertToIcns" "/var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconinfer--26188-2H8dD19rVveH/icon.png" "/var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconconv--26188-lbKOjKK53S7Y/icon.icns"
Conversion succeeded and produced icon at /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconconv--26188-lbKOjKK53S7Y/icon.icns
Copying icons if necessary
No copying necessary on macOS; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v12.13.0
  electron-packager Host Operating system: darwin 19.6.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-app--26188-eD8hoeUp2kKQ","electronVersion":"11.3.0","icon":"/var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconconv--26188-lbKOjKK53S7Y/icon.icns","name":"Pandora","out":"/Users/TheCleric/Downloads/Pandora","overwrite":true,"platform":"darwin","targetUrl":"https://www.pandora.com/","tmpdir":false,"win32metadata":{"ProductName":"Pandora","InternalName":"Pandora","FileDescription":"Pandora"}} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-app--26188-eD8hoeUp2kKQ/package.json +0ms
  electron-packager Application name: Pandora +7ms
  electron-packager Target Electron version: 11.3.0 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"11.3.0","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v11.3.0
  electron-packager Creating /Users/TheCleric/Downloads/Pandora/darwin-x64-template +4ms
  electron-packager Extracting /Users/TheCleric/Library/Caches/electron/ad7d1b1b49693bf7121ef728679aa91bceed390f6a4afb9f94f1cff5be54639b/electron-v11.3.0-darwin-x64.zip to /Users/TheCleric/Downloads/Pandora/darwin-x64-template +1ms
  electron-packager Initializing app in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64 from /Users/TheCleric/Downloads/Pandora/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/Users/TheCleric/Downloads/Pandora' ] +2s
  electron-packager Copying icon "/var/folders/72/qw4nfb551g565ct_dc1j22fh0000gp/T/nativefier-14-19-20-iconconv--26188-lbKOjKK53S7Y/icon.icns" to app's Resources as "electron.icns" +0ms
  electron-packager Renaming Electron to Pandora in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/MacOS +915ms
  electron-packager Renaming Electron Helper to Pandora Helper in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Renderer) to Pandora Helper (Renderer) in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (Plugin) to Pandora Helper (Plugin) in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Pandora Helper (GPU) in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Pandora Helper.app in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Pandora Helper (Renderer).app in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Pandora Helper (Plugin).app in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper (GPU).app to Pandora Helper (GPU).app in /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to /Users/TheCleric/Downloads/Pandora/Pandora-darwin-x64 , move it wherever it makes sense for you and run the app bundle.
```

**Expected behavior**

The media keys to control the built app.

**Actual behavior**

The media keys do not control the built app

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: 42.2.1
 - Node.js: 12.13.0
 - Npm: 6.12.0
 - OS: Mac OS 10.15.7
 - Is it a regression? If yes, what's the last working / first broken version? Not to my knowledge.
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

### PR DESCRIPTION
**Pull request by TheCleric**
When setting a media key (play, pause, next/previous track) as global shortcut in Mac OS 10.14+, accessibility permissions must be given to the app for it to work (see https://www.electronjs.org/docs/api/global-shortcut?q=MediaPlayPause#globalshortcutregisteraccelerator-callback).

This PR will accomplish the following on generated app launch:
- Check if global shortcuts are being setup
- Check if the host OS is Mac OS
- Check if the global shortcuts were one of the media keys
- If the above are true, check if the app has accessibility permissions
- If the app does not have the accessibility permissions it will ask the user if they would like to be prompted for these permissions, and then ask Mac OS to prompt for accessibility permissions.

~~As well, a new command line flag is added (`--no-accessibility-prompt`) to preventatively suppress these prompts if desired.~~

Screenshots of the new behavior:
Screen Shot 2021-02-26 at 2 41 21 PM
Screen Shot 2021-02-26 at 2 41 28 PM
Screen Shot 2021-02-26 at 2 41 50 PM

### CODE REVIEW

**Comment by TheCleric** [comment]
Screenshots of the new behavior:
Screen Shot 2021-02-26 at 2 41 21 PM
Screen Shot 2021-02-26 at 2 41 28 PM
Screen Shot 2021-02-26 at 2 41 50 PM

**Comment by TheCleric** [comment]
Sample command to run on Mac to generate and app that will experience this new behavior:

`nativefier --global-shortcuts ~/Downloads/nativefier-media-keys.json -n "Pandora" https://www.pandora.com`

File: app/src/components/mainWindow.ts [hunk 1]
```diff
@@ -72,6 +72,16 @@ function setProxyRules(browserWindow: BrowserWindow, proxyRules): void {
   });
 }
 
+export function saveAppArgs(appArgs, filePath) {
```
Comment (ronjouch) [inline app/src/components/mainWindow.ts:75]: 1. `appArgs` → `newAppArgs: any`, pls
2. Why make `filePath` an argument? Why not make `saveAppArgs` always write at `APP_ARGS_FILE_PATH`, so that the caller is only concerned with passing the new app args?

File: app/src/main.ts [hunk 2]
```diff
@@ -168,6 +169,52 @@ if (shouldQuit) {
...
+      if (isOSX() && appArgs.accessibilityPrompt) {
+        const mediaKeys = [
+          'MediaPlayPause',
+          'MediaNextTrack',
+          'MediaPreviousTrack',
+          'MediaStop',
+        ];
+        const globalShortcutsKeys = appArgs.globalShortcuts.map((g) => g.key);
+        const mediaKeyWasSet =
+          globalShortcutsKeys.filter((g) => mediaKeys.includes(g)).length > 0;
```
Comment (ronjouch) [inline app/src/main.ts:182]: Nit: no need to look at the whole array, let's stop at the first match:

```suggestion
        const mediaKeyWasSet =
          globalShortcutsKeys.find((g) => mediaKeys.includes(g));
```

File: app/src/main.ts [hunk 3]
```diff
@@ -168,6 +169,52 @@ if (shouldQuit) {
...
+        if (
+          mediaKeyWasSet &&
+          !systemPreferences.isTrustedAccessibilityClient(false)
+        ) {
+          // Since we're tryig to set global keyboard shortcuts for media keys, we need to prompt
+          // the user for permission on Mac.
+          // For reference:
+          // https://www.electronjs.org/docs/api/global-shortcut?q=MediaPlayPause#globalshortcutregisteraccelerator-callback
```
Comment (ronjouch) [inline app/src/main.ts:190]: 👍, good commenting, thx.

File: app/src/main.ts [hunk 4]
```diff
@@ -168,6 +169,52 @@ if (shouldQuit) {
...
+          //
```
Comment (ronjouch) [inline app/src/main.ts:191]:
```suggestion
```

File: app/src/main.ts [hunk 5]
```diff
@@ -168,6 +169,52 @@ if (shouldQuit) {
...
+          const accessibilityPromptResult = dialog.showMessageBoxSync(null, {
+            type: 'question',
+            message: 'Accessibility Permissions Needed',
+            buttons: ['Yes', 'No', 'Never Ask Me Again'],
+            defaultId: 0,
+            detail:
+              `${appArgs.name} would like to use one or more of your keyboard's media keys (start, stop, next track, or previous track) to control it.\n\n` +
+              `Would you like Mac OS to ask for your permission to do so?\n\n` +
+              `If so, you will need to restart ${appArgs.name} after granting permissions for these keyboard shortcuts to begin working.`,
```
Comment (ronjouch) [inline app/src/main.ts:200]: I'd rather have a simple `Yes` / `Not now` dialog, without this "Never ask me again" option, and an extra line that says something like:

```
If you don't want to / cannot grant ${appArgs.name} Accessibility permissions, please delete the global shortcuts using media keys to not be prompted again.
```

A macOS user who wants to use a media key in a global shortcut has no choice but to comply to grant accessibility permissions, correct?

So, why this new `no-accessibility-prompt` flag, and the need to persist it?

To me, users confronted to this dialog will fall into two buckets:

1. "Accepters", who want their media key global shortcut and accept to enable it at macOS level
2. "Denyers", who would like their media key global shortcut, but for some reason don't want to enable the accessibility setting, and should then simply remove the shortcut from their shortcut options.

Why make things more complex with a third bucket, a new flag, and more persistence needed? You don't want to enable the accessibility thing, alright, we tell you why you can't use your global shortcut. Want us to stop telling you? A. do the OS requirement, or B. get rid of the binding (which at that point was broken anyway). Simple and doesn't need an extra flag, of which Nativefier already has waaaaaaaaaaaaaay too many 😄.

Am I missing something?

File: package.json [hunk 6]
```diff
@@ -38,7 +38,7 @@
     "changelog": "./docs/generate-changelog",
     "ci": "npm run lint && npm test",
     "clean": "rimraf lib/ app/lib/ app/dist/",
-    "clean:full": "rimraf lib/ app/lib/ app/dist/ node_modules/ app/node_modules/",
+    "clean:full": "rimraf lib/ app/lib/ app/dist/ app/node_modules/ node_modules/",
```
Comment (ronjouch) [inline package.json:41]: Thanks 🙂

**Review by ronjouch — CHANGES_REQUESTED** [review]
Hi @TheCleric , nice work, thanks! I have a few nits and one main concern:

File: app/src/main.ts (hunk 5 above)
Comment (TheCleric) [reply app/src/main.ts:200]: I could be argued out of it, I was just trying to accomplish two things:
1) If someone is creating an app for distribution, they could disable this prompt if they felt like it would be too intrusive.
2) If someone was downloading a distributed app, they could opt out of this feature without being pestered every time they launch it.

I do get the argument that Nativefier has too many flags though. 😆

Comment (ronjouch) [reply app/src/main.ts:200]: Okay, now I understand. Take 2: what about reworking it so that you keep the “do not ask again” persistence, but without the extra flag?

That way, someone using a distributed bundle will at least be warned once that the keyboard shortcut cannot work, and will be able to decide what to do. It’s a pestering, but a single/minor one, and it allows for a bit of feedback / communication between users and packagers. Else, the shortcut will simply be invisibly dead to bundle users.

With a bit of tweaking the dialog box text, I think it can be made friendly and understandable.

Waddayathink?

Comment (TheCleric) [reply app/src/main.ts:199]: That sounds like a fair compromise. :)

How do you think we should tweak the dialog text in that case? I was trying to communicate to the user that they were about to get a big scary dialog asking for permissions that don't seem particularly related to the app itself, even though they are. However, I get that just because it's clear to me doesn't mean it will be to an end user. 😆

Comment (TheCleric) [reply app/src/main.ts:202]: Command option removed.

File: docs/api.md [hunk 7]
```diff
@@ -69,6 +69,7 @@
   - [[global-shortcuts]](#global-shortcuts)
   - [[browserwindow-options]](#browserwindow-options)
   - [[darwin-dark-mode-support]](#darwin-dark-mode-support)
+  - [[no-accessibility-prompt]](#no-accessibility-prompt)
```
Comment (ronjouch) [inline docs/api.md:72]: Leftover to remove.

```suggestion
```

File: src/options/optionsMain.ts [hunk 8]
```diff
@@ -47,6 +47,7 @@ export async function getOptions(rawOptions: any): Promise<AppOptions> {
       },
     },
     nativefier: {
+      accessibilityPrompt: true,
```
Comment (ronjouch) [inline src/options/optionsMain.ts:50]: Okay, I like that you left it in the model as explicitly constantly true; if someone absolutely needs to disable it they can tweak the JSON manually, and we'll easily re-introduce the option that I got you to remove if user reports make us realize it was actually strongly required for legit use cases. 👍.

File: app/src/main.ts [hunk 9]
```diff
@@ -168,6 +171,52 @@ if (shouldQuit) {
...
+          !systemPreferences.isTrustedAccessibilityClient(false)
+        ) {
+          // Since we're tryig to set global keyboard shortcuts for media keys, we need to prompt
+          // the user for permission on Mac.
+          // For reference:
+          // https://www.electronjs.org/docs/api/global-shortcut?q=MediaPlayPause#globalshortcutregisteraccelerator-callback
+          const accessibilityPromptResult = dialog.showMessageBoxSync(null, {
+            type: 'question',
+            message: 'Accessibility Permissions Needed',
+            buttons: ['Yes', 'No', 'Never Ask Me Again'],
```
Comment (ronjouch) [inline app/src/main.ts:197]:
```suggestion
            buttons: ['Yes', 'No', 'No and never ask again'],
```

File: app/src/main.ts [hunk 10]
```diff
@@ -168,6 +171,52 @@ if (shouldQuit) {
...
+            defaultId: 0,
+            detail:
+              `${appArgs.name} would like to use one or more of your keyboard's media keys (start, stop, next track, or previous track) to control it.\n\n` +
+              `Would you like Mac OS to ask for your permission to do so?\n\n` +
+              `If so, you will need to restart ${appArgs.name} after granting permissions for these keyboard shortcuts to begin working.`,
```
Comment (ronjouch) [inline app/src/main.ts:202]: Here's my try to make the consequences of each choice fully explicit (and staying concise, which isn't easy).

```suggestion
              `${appArgs.name} needs macOS permissions to enable your Global Shortcuts using media keys (Start, Stop, Next/Previous track).\n\n` +
              `- "Yes" will open macOS' Accessibility Settings, where we need you to check ${appArgs.name}. Please then restart the app, and your Global Shortcuts will work.\n\n` +
              `- "No" will skip this setup for now. Your Global Shortcuts using media keys will not work, and you will be prompted next time the app starts.\n\n` +
              `- "No and never ask again" will never bother you again about it. Your Global Shortcuts using media keys will not work.`,
```

File: app/src/main.ts [hunk 11]
```diff
@@ -168,6 +171,52 @@ if (shouldQuit) {
...
+          mediaKeyWasSet &&
+          !systemPreferences.isTrustedAccessibilityClient(false)
+        ) {
+          // Since we're tryig to set global keyboard shortcuts for media keys, we need to prompt
+          // the user for permission on Mac.
+          // For reference:
+          // https://www.electronjs.org/docs/api/global-shortcut?q=MediaPlayPause#globalshortcutregisteraccelerator-callback
+          const accessibilityPromptResult = dialog.showMessageBoxSync(null, {
+            type: 'question',
+            message: 'Accessibility Permissions Needed',
```
Comment (ronjouch) [inline app/src/main.ts:196]:
```suggestion
            message: 'Permissions needed to enable Global Shortcuts using Media Keys',
```

?

**Review by ronjouch — COMMENTED** [review]
Neat, thanks for the fixes!

I have one last doc nit, and an attempt to improve the dialog box copy. What do you think about it?

File: app/src/main.ts (hunk 10 above)
Comment (ronjouch) [reply app/src/main.ts:202]: Damn, now that I re-read this, I think this is too dense / maybe overwhelming, and maybe your version was better.

Oh well, pick stuff that you like, or nothing, and tell me when you're happy about it.

Comment (TheCleric) [reply app/src/main.ts:202]: Perhaps it is pride, but I like mine better for the following reason: a downstream user may have no idea what we mean here by a global shortcut.

**Comment by TheCleric** [comment]
I think it's where I'd personally leave it at.

File: app/src/main.ts [hunk 12]
```diff
@@ -168,6 +171,52 @@ if (shouldQuit) {
...
+        ];
+        const globalShortcutsKeys = appArgs.globalShortcuts.map((g) => g.key);
+        const mediaKeyWasSet = globalShortcutsKeys.find((g) =>
+          mediaKeys.includes(g),
+        );
+        if (
+          mediaKeyWasSet &&
+          !systemPreferences.isTrustedAccessibilityClient(false)
+        ) {
+          // Since we're tryig to set global keyboard shortcuts for media keys, we need to prompt
```
Comment (ronjouch) [inline app/src/main.ts:190]:
```suggestion
          // Since we're trying to set global keyboard shortcuts for media keys, we need to prompt
```

**Review by ronjouch — APPROVED** [review]
Thaaaaaaaaaaaanks @TheCleric ! Merging.

**Comment by ronjouch** [comment]
Released in v42.4.0. Thanks!
