### PR TITLE
Fix `--tray start-in-tray` (fix #1225)

### LINKED ISSUE #1225: --tray start-in-tray, --width, --height not working in Windows
i'm a nativefier noob so i'm not sure if that is the intended effect... i can't get start-in-tray to work at all, nor the width or height. the "start-in-tray" modifier especially messes with the entire operation and ends up making a subfolder for the app called start-in-tray.

### PR DESCRIPTION
**Pull request by TheCleric**
Resolves #1225

### CODE REVIEW

File: app/src/components/mainWindow.ts [hunk 1]
```diff
@@ -146,7 +146,7 @@ function createContextMenu(options, window: BrowserWindow): void {
 
 export function saveAppArgs(newAppArgs: any): void {
   try {
-    fs.writeFileSync(APP_ARGS_FILE_PATH, JSON.stringify(newAppArgs));
+    fs.writeFileSync(APP_ARGS_FILE_PATH, JSON.stringify(newAppArgs, null, 2));
```
Comment (ronjouch) [inline app/src/components/mainWindow.ts:149]: good idea

**Review by ronjouch — APPROVED** [review]

**Comment by ronjouch** [comment]
@TheCleric this regresses tray icons on Linux (at least), by causing tray to be ON even though I didn't ask for it. Here's `test:manual` without and with this PR. As you see, with this PR, tray icon was enabled even though I didn't ask for it.

Also, as obvious in screenshot 2 below, our tray icon is horribly broken and consumes all available horizontal space, but I notice this was already the case before a491e3496675d7eef302ce2458332d0ef434b507. It for sure hasn't always been the case (I've tested it on Linux when it was introduced), but I dunno yet if it's a regression in GNOME / kstatusnotifiericon extension, or ours (and when it was introduced if it's ours). Filed separate issue https://github.com/nativefier/nativefier/issues/1237 for this.

- Without a491e3496675d7eef302ce2458332d0ef434b507: tray is off in `test:manual`
  screenshot_tray-okay_2021-06-22-08:15:00
- With a491e3496675d7eef302ce2458332d0ef434b507: tray is ON in `test:manual` (again, pls ignore the GNOME shell bug)
  screenshot_tray-broken_2021-06-22-08:16:38


<details>
  <summary>Logs for <code>npm run test:manual</code> with verbose CLI & app</summary>

```
08:18:32 /o/nativefier (master) npm run test:manual

> nativefier@44.0.4 test:manual
> npm run build && ./.github/manual-test


> nativefier@44.0.4 build
> npm run clean && tsc --build . app && npm run build-app && npm run build-app-static


> nativefier@44.0.4 clean
> rimraf coverage/ lib/ app/lib/ app/dist/


> nativefier@44.0.4 build-app
> cd app && webpack

asset main.js 467 KiB [emitted] (name: main) 1 related asset
runtime modules 123 bytes 1 module
modules by path ./node_modules/ 390 KiB
  modules by path ./node_modules/source-map/ 99.4 KiB 11 modules
  modules by path ./node_modules/electron-squirrel-startup/ 18.7 KiB 6 modules
  modules by path ./node_modules/graceful-fs/*.js 21.8 KiB 4 modules
  modules by path ./node_modules/color-convert/*.js 20.5 KiB 3 modules
  modules by path ./node_modules/source-map-support/*.js 19.3 KiB 2 modules
  modules by path ./node_modules/mime-db/ 141 KiB 2 modules
modules by path ./src/ 68.8 KiB
  modules by path ./src/components/*.ts 28.9 KiB 5 modules
  modules by path ./src/helpers/*.ts 25.8 KiB 4 modules
  ./src/main.ts 14 KiB [built] [code generated]
11 modules
webpack 5.40.0 compiled successfully in 4065 ms

> nativefier@44.0.4 build-app-static
> ncp app/src/static/ app/lib/static/ && ncp app/dist/preload.js app/lib/preload.js && ncp app/dist/preload.js.map app/lib/preload.js.map


***** SMOKE TEST 1: Setting up test and building app... *****
/opt/nativefier /opt/nativefier
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform linux

Performing async options post-processing.
Inferring icon for https://npmjs.com/ on linux
Inferring icon from store for https://npmjs.com/ on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Sanitized filename for nativefier-smoke-test-1 : nativefier-smoke-test-1
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Got an icon from the page.
Writing 1.7 kb icon to /tmp/nativefier-8-18-48-iconinfer--207434-u6MENjW6638u/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/opt/nativefier/app',
    electronVersion: '12.0.11',
    icon: '/tmp/nativefier-8-18-48-iconinfer--207434-u6MENjW6638u/icon.png',
    name: 'nativefier-smoke-test-1',
    out: '/tmp/nativefier-manual-test-DUmCD',
    overwrite: true,
    platform: 'linux',
    portable: false,
    targetUrl: 'https://npmjs.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'nativefier-smoke-test-1',
      InternalName: 'nativefier-smoke-test-1',
      FileDescription: 'nativefier-smoke-test-1'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [
      '/tmp/nativefier-manual-test-DUmCD/resources/inject.css',
      '/tmp/nativefier-manual-test-DUmCD/resources/inject.js'
    ],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '44.0.4',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /opt/nativefier/app to /tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE
Writing app config to /tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/nativefier.json
Copying 2 files to inject in app.
Copying injection file "/tmp/nativefier-manual-test-DUmCD/resources/inject.css" to "/tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/inject/inject-5b35d3.css"
Copying injection file "/tmp/nativefier-manual-test-DUmCD/resources/inject.js" to "/tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/inject/inject-571148.js"
Updating /tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/package.json 'name' field to nativefier-smoke-test-1-nativefier-411f25

Converting icons...
Building for Linux and icon is already a .png, no conversion needed
Copying icons if necessary
Copying icon /tmp/nativefier-8-18-48-iconinfer--207434-u6MENjW6638u/icon.png to /tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/icon.png

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v16.3.0
  electron-packager Host Operating system: linux 5.12.12-zen1-1-zen (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE","electronVersion":"12.0.11","icon":"/tmp/nativefier-8-18-48-iconinfer--207434-u6MENjW6638u/icon.png","name":"nativefier-smoke-test-1","out":"/tmp/nativefier-manual-test-DUmCD","overwrite":true,"platform":"linux","portable":false,"targetUrl":"https://npmjs.com/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"nativefier-smoke-test-1","InternalName":"nativefier-smoke-test-1","FileDescription":"nativefier-smoke-test-1"}} +0ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-8-18-48-app--207434-CAx0p0oXxcEE/package.json +0ms
  electron-packager Application name: nativefier-smoke-test-1 +5ms
  electron-packager Target Electron version: 12.0.11 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"12.0.11","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v12.0.11
  electron-packager Creating /tmp/nativefier-manual-test-DUmCD/linux-x64-template +2ms
  electron-packager Extracting /home/ronj/.cache/electron/e0e0fe687c746f830a615f37fe4a2f2e9629a4ed38a6ab119cb562152366c859/electron-v12.0.11-linux-x64.zip to /tmp/nativefier-manual-test-DUmCD/linux-x64-template +1ms
  electron-packager Initializing app in /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64 from /tmp/nativefier-manual-test-DUmCD/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/tmp/nativefier-manual-test-DUmCD' ] +2s
  electron-packager Renaming electron to nativefier-smoke-test-1 in /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64 +150ms

Finalizing build...
App built to /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries

***** SMOKE TEST 1: Test checklist *****
- Injected js: should show an alert saying hello
- Injected css: should make npmjs all blue
- Internal links open internally
- External links open in browser
- Keyboard shortcuts: {back, forward, zoom in/out/zero} work
- Console: no Electron runtime deprecation warnings/error logged
*** Running app
appArgs {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  arch: 'x64',
  asar: false,
  blockExternalUrls: false,
  bounce: false,
  buildDate: 1624364330626,
  clearCache: false,
  counter: false,
  darwinDarkModeSupport: false,
  disableContextMenu: false,
  disableDevTools: false,
  disableGpu: false,
  disableOldBuildWarning: false,
  electronVersionUsed: '12.0.11',
  enableEs3Apis: false,
  fastQuit: false,
  fullScreen: false,
  height: 800,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  isUpgrade: false,
  maximize: false,
  name: 'nativefier-smoke-test-1',
  nativefierVersion: '44.0.4',
  portable: false,
  showMenuBar: false,
  singleInstance: false,
  targetUrl: 'https://npmjs.com/',
  tray: 'false',
  userAgentHonest: false,
  width: 1280,
  widevine: false,
  win32metadata: {
    ProductName: 'nativefier-smoke-test-1',
    InternalName: 'nativefier-smoke-test-1',
    FileDescription: 'nativefier-smoke-test-1'
  },
  zoom: 1,
  oldBuildWarningText: ''
}
Not loading override URL passed as argument, because failed to parse: --verbose TypeError [ERR_INVALID_URL]: Invalid URL: --verbose
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at Object.<anonymous> (/tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/src/main.ts:67:5)
    at __webpack_require__ (/tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/webpack/bootstrap:19:1)
    at /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/webpack/startup:4:1
    at Object.<anonymous> (/tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/lib/main.js:10993:12)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14) {
  input: '--verbose',
  code: 'ERR_INVALID_URL'
}
ready
getDefaultWindowOptions {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364330626,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'nativefier-smoke-test-1',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: 'false',
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'nativefier-smoke-test-1',
      InternalName: 'nativefier-smoke-test-1',
      FileDescription: 'nativefier-smoke-test-1'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  webPreferences: {},
  defaultOptions: {
    fullscreenable: true,
    tabbingIdentifier: undefined,
    title: 'nativefier-smoke-test-1',
    webPreferences: {
      javascript: true,
      nodeIntegration: false,
      preload: '/tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/lib/preload.js',
      plugins: true,
      webSecurity: true,
      zoomFactor: 1
    }
  }
}
app.browser-window-created {
  event: {
    preventDefault: [Function: preventDefault],
    sendReply: [Function: sendReply]
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged]
    },
    _eventsCount: 7
  }
}
Injecting CSS file /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/inject/inject-5b35d3.css
createMenu {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364330626,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'nativefier-smoke-test-1',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: 'false',
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'nativefier-smoke-test-1',
      InternalName: 'nativefier-smoke-test-1',
      FileDescription: 'nativefier-smoke-test-1'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  mainWindow: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Function (anonymous)],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Function: closedHandler]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
initContextMenu {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364330626,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'nativefier-smoke-test-1',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: 'false',
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'nativefier-smoke-test-1',
      InternalName: 'nativefier-smoke-test-1',
      FileDescription: 'nativefier-smoke-test-1'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Function (anonymous)],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Function: closedHandler]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
Injecting CSS file /tmp/nativefier-manual-test-DUmCD/nativefier-smoke-test-1-linux-x64/resources/app/inject/inject-5b35d3.css
app.browser-window-focus {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
mainWindow.focus
browserWindow.webContents.did-navigate https://www.npmjs.com/
browserWindow.webContents.did-navigate https://www.npmjs.com/
onHeadersReceived {
  contentType: 'text/css',
  resourceType: 'stylesheet',
  url: 'https://static.npmjs.com/styles.9da0f13756bc1f840a91.css'
}
Skipping CSS injection for:
https://static.npmjs.com/styles.9da0f13756bc1f840a91.css
with resourceType stylesheet and content-type text/css
onHeadersReceived {
  contentType: 'image/png',
  resourceType: 'image',
  url: 'https://static.npmjs.com/attachments/ck3uweazy72ye8874y9kkxnx1-gak.png'
}
Skipping CSS injection for:
https://static.npmjs.com/attachments/ck3uweazy72ye8874y9kkxnx1-gak.png
with resourceType image and content-type image/png
onHeadersReceived {
  contentType: 'text/css; charset=utf-8',
  resourceType: 'stylesheet',
  url: 'https://fonts.googleapis.com/css?family=Arimo|Poppins:400,600,700&display=swap'
}
Skipping CSS injection for:
https://fonts.googleapis.com/css?family=Arimo|Poppins:400,600,700&display=swap
with resourceType stylesheet and content-type text/css; charset=utf-8
onHeadersReceived {
  contentType: 'application/javascript',
  resourceType: 'script',
  url: 'https://static.npmjs.com/commons.55a758a952d29984a739.js'
}
Skipping CSS injection for:
https://static.npmjs.com/commons.55a758a952d29984a739.js
with resourceType script and content-type application/javascript
onHeadersReceived {
  contentType: 'application/javascript',
  resourceType: 'script',
  url: 'https://static.npmjs.com/minicssextractbug.c9e6dea3bfff5666771b.js'
}
Skipping CSS injection for:
https://static.npmjs.com/minicssextractbug.c9e6dea3bfff5666771b.js
with resourceType script and content-type application/javascript
onHeadersReceived {
  contentType: 'application/javascript',
  resourceType: 'script',
  url: 'https://static.npmjs.com/homepage/homepage.46dbecfaefcf612cafb9.js'
}
Skipping CSS injection for:
https://static.npmjs.com/homepage/homepage.46dbecfaefcf612cafb9.js
with resourceType script and content-type application/javascript
onHeadersReceived {
  contentType: 'image/png',
  resourceType: 'image',
  url: 'https://static.npmjs.com/attachments/ck49cu3ceh1sust74dkzkfn69-grey-logowall.png'
}
Skipping CSS injection for:
https://static.npmjs.com/attachments/ck49cu3ceh1sust74dkzkfn69-grey-logowall.png
with resourceType image and content-type image/png
onHeadersReceived {
  contentType: 'text/css; charset=utf-8',
  resourceType: 'stylesheet',
  url: 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600'
}
Skipping CSS injection for:
https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600
with resourceType stylesheet and content-type text/css; charset=utf-8
onHeadersReceived {
  contentType: 'text/css; charset=utf-8',
  resourceType: 'stylesheet',
  url: 'https://fonts.googleapis.com/css?family=Fira+Mono'
}
Skipping CSS injection for:
https://fonts.googleapis.com/css?family=Fira+Mono
with resourceType stylesheet and content-type text/css; charset=utf-8
onHeadersReceived {
  contentType: 'text/css; charset=utf-8',
  resourceType: 'stylesheet',
  url: 'https://fonts.googleapis.com/css?family=Poppins:400,500,600'
}
Skipping CSS injection for:
https://fonts.googleapis.com/css?family=Poppins:400,500,600
with resourceType stylesheet and content-type text/css; charset=utf-8
onHeadersReceived {
  contentType: 'image/png',
  resourceType: 'image',
  url: 'https://static.npmjs.com/abf53a31b2da4657a1a004ee9358551c.png'
}
Skipping CSS injection for:
https://static.npmjs.com/abf53a31b2da4657a1a004ee9358551c.png
with resourceType image and content-type image/png
onHeadersReceived {
  contentType: 'image/png',
  resourceType: 'image',
  url: 'https://static.npmjs.com/3dc2ca3d2e53fc894b904d917cf90015.png'
}
Skipping CSS injection for:
https://static.npmjs.com/3dc2ca3d2e53fc894b904d917cf90015.png
with resourceType image and content-type image/png
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/sourcesanspro/v14/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/sourcesanspro/v14/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJfecg.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/poppins/v15/pxiEyp8kv8JHgFVrJJfecg.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwlxdu.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/sourcesanspro/v14/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwlxdu.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/firamono/v9/N0bX2SlFPv1weGeLZDtgJv7S.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/firamono/v9/N0bX2SlFPv1weGeLZDtgJv7S.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/poppins/v15/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2
with resourceType other and content-type font/woff2
onHeadersReceived {
  contentType: 'font/woff2',
  resourceType: 'other',
  url: 'https://fonts.gstatic.com/s/arimo/v17/P5sfzZCDf9_T_3cV7NCUECyoxNk37cxcABrB.woff2'
}
Skipping CSS injection for:
https://fonts.gstatic.com/s/arimo/v17/P5sfzZCDf9_T_3cV7NCUECyoxNk37cxcABrB.woff2
with resourceType other and content-type font/woff2
app.browser-window-blur {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
app.browser-window-focus {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
mainWindow.focus
app.browser-window-blur {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
app.browser-window-focus {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
mainWindow.focus
sendParamsOnDidFinishLoad.window.webContents.did-finish-load https://www.npmjs.com/
sendParamsOnDidFinishLoad.window.webContents.did-finish-load https://www.npmjs.com/
app.quit {
  event: {
    preventDefault: [Function: preventDefault],
    sender: App {
      quit: [Function: quit],
      exit: [Function: exit],
      focus: [Function: focus],
      getVersion: [Function: getVersion],
      setVersion: [Function: setVersion],
      getName: [Function: getName],
      setName: [Function: setName],
      isReady: [Function: isReady],
      whenReady: [Function: whenReady],
      addRecentDocument: [Function: addRecentDocument],
      clearRecentDocuments: [Function: clearRecentDocuments],
      setAppUserModelId: [Function: setAppUserModelId],
      isDefaultProtocolClient: [Function: isDefaultProtocolClient],
      setAsDefaultProtocolClient: [Function: setAsDefaultProtocolClient],
      removeAsDefaultProtocolClient: [Function: removeAsDefaultProtocolClient],
      getApplicationNameForProtocol: [Function: getApplicationNameForProtocol],
      setBadgeCount: [Function: setBadgeCount],
      getBadgeCount: [Function: getBadgeCount],
      getLoginItemSettings: [Function: getLoginItemSettings],
      setLoginItemSettings: [Function: setLoginItemSettings],
      isEmojiPanelSupported: [Function: isEmojiPanelSupported],
      setAboutPanelOptions: [Function: setAboutPanelOptions],
      showAboutPanel: [Function: showAboutPanel],
      isUnityRunning: [Function: isUnityRunning],
      setAppPath: [Function: setAppPath],
      getAppPath: [Function: getAppPath],
      setPath: [Function: setPath],
      getPath: [Function: getPath],
      setAppLogsPath: [Function: setAppLogsPath],
      setDesktopName: [Function: setDesktopName],
      getLocale: [Function: getLocale],
      getLocaleCountryCode: [Function: getLocaleCountryCode],
      importCertificate: [Function: importCertificate],
      hasSingleInstanceLock: [Function: hasSingleInstanceLock],
      requestSingleInstanceLock: [Function: requestSingleInstanceLock],
      releaseSingleInstanceLock: [Function: releaseSingleInstanceLock],
      relaunch: [Function: relaunch],
      isAccessibilitySupportEnabled: [Function: isAccessibilitySupportEnabled],
      setAccessibilitySupportEnabled: [Function: setAccessibilitySupportEnabled],
      disableHardwareAcceleration: [Function: disableHardwareAcceleration],
      disableDomainBlockingFor3DAPIs: [Function: disableDomainBlockingFor3DAPIs],
      getFileIcon: [Function: getFileIcon],
      getAppMetrics: [Function (anonymous)],
      getGPUFeatureStatus: [Function: getGPUFeatureStatus],
      getGPUInfo: [Function: getGPUInfo],
      userAgentFallback: [Getter/Setter],
      enableSandbox: [Function: enableSandbox],
      allowRendererProcessReuse: [Getter/Setter],
      commandLine: [Object],
      isPackaged: true,
      _setDefaultAppPaths: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 17
    }
  },
  exitCode: 0
}

Did everything work as expected? [yN] n
```
</details>

**Comment by TheCleric** [comment]
@ronjouch the fix for this was related to the change to `yargs` over `commander`. So I'd suggest installing v43.1.3 and see what the behavior is.

**Comment by ronjouch** [comment]
> @ronjouch the fix for this was related to the change to `yargs` over `commander`. So I'd suggest installing v43.1.3 and see what the behavior is.

@TheCleric mmmmmh I think you misunderstood what I wrote / missed something: before your PR commit, tray wasn't incorrectly set to true. No need to test down to 43.1.3, it's this commit.

**Comment by TheCleric** [comment]
Sorry, was conflating the two issues. I was more referring to

> Also, as obvious in screenshot 2 below, our tray icon is horribly broken and consumes all available horizontal space, but I notice this was already the case before a491e34. It for sure hasn't always been the case (I've tested it on Linux when it was introduced), but I dunno yet if it's a regression in GNOME / kstatusnotifiericon extension, or ours (and when it was introduced if it's ours).

So that you could disambiguate between GNOME issues and our issues.
