### PR TITLE
Fix tabs opening twice (fix #1209)

### LINKED ISSUE #1209: Apps w/ --single-instance will open two tabs when opening into a new tab
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

After upgrading to latest, multiple apps now open two (2) tabs when the link previously would open into a single tab.

An example would be in Gmail, clicking Google Apps upper right, and then selecting an app that would be a new tab will result in two tabs of the same app.

**Steps to reproduce**

```
nativefier 'https://docs.google.com/spreadsheets'  --single-instance
```

**Expected behavior**

One tab will open.

**Actual behavior**

Two tabs will open.

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: 43.1.3
 - Node.js: v14.15.4
 - Npm: 7.15.1
 - OS: OS X Catalina 10.15.7

### PR DESCRIPTION
**Pull request by TheCleric**
By adding a new window handler only to the main window.

### CODE REVIEW

File: app/src/components/mainWindow.ts [hunk 1]
```diff
@@ -88,6 +88,30 @@ export async function createMainWindow(
...
+  // We can't quite cut over to that yet for a few reasons:
+  // 1. Our version of Electron does not yet support a parameter to
+  //    setWindowOpenHandler that contains `disposition', which we need.
+  //    See https://github.com/electron/electron/issues/28380
+  // 2. setWindowOpenHandler doesn't support newGuest as well
+  // Though at this point, 'new-window' bugs seem to be coming up and downstream
+  // users are being pointed to use setWindowOpenHandler.
+  // E.g., https://github.com/electron/electron/issues/28374
+
+  mainWindow.webContents.on(
```
Comment (ronjouch) [inline app/src/components/mainWindow.ts:101]:
```suggestion
  // Note it is important to add this handler only to the *main* window,
  // else we run into weird behavior like opening tabs twice
  mainWindow.webContents.on(
```

**Review by ronjouch — APPROVED** [review]
👍. Suggesting an extra comment about the bug we faced. Letting you accept/improve it, and merge.
