### PR TITLE
Docker: fix Windows builds (fix #997), line endings, switch to Alpine

### LINKED ISSUE #890: How to create apps for all platforms on Alpine Linux?
Hello.

OS: `Alpine 3.11`

```bash
# npm -v
6.13.4
# node -v
v12.14.0
# nativefier -v
7.7.0
```
Installed wine:
```
 # apk add wine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/14) Installing libxau (1.0.9-r0)
(2/14) Installing libbsd (0.10.0-r0)
(3/14) Installing libxdmcp (1.1.3-r0)
(4/14) Installing libxcb (1.13.1-r0)
(5/14) Installing libx11 (1.6.9-r0)
(6/14) Installing libxext (1.3.4-r0)
(7/14) Installing alsa-lib (1.2.1.2-r0)
(8/14) Installing eudev-libs (3.2.9-r1)
(9/14) Installing spirv-tools (2019.5-r0)
(10/14) Installing vkd3d (1.1-r0)
(11/14) Installing xz-libs (5.2.4-r0)
(12/14) Installing libxml2 (2.9.10-r1)
(13/14) Installing wine-libs (4.0.3-r0)
(14/14) Installing wine (4.0.3-r0)
Executing busybox-1.31.1-r8.trigger
OK: 412 MiB in 79 packages
```
Error create app for windows:
```bash
# nativefier --name "Hello" -p "windows" "https://google.com"
Downloading tmp-283-0-electron-v5.0.10-win32-x64.zip
[============================================>] 100.0% of 58.71 MB (10.21 MB/s)
  packaging [=====================================             ] 74%Packaging app for platform win32 x64 using electron v5.0.10
  packaging [========================================          ] 79%Error: Could not find "wine" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: [
    '/usr/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe',
    '/home/google/Hello-win32-x64/Hello.exe',
    '--set-version-string',
    'FileDescription',
    'Hello',
    '--set-version-string',
    'InternalName',
    'Hello',
    '--set-version-string',
    'OriginalFilename',
    'Hello.exe',
    '--set-version-string',
    'ProductName',
    'Hello',
    '--set-version-string',
    'CompanyName',
    'Jia Hao',
    '--set-file-version',
    '1.0.0',
    '--set-product-version',
    '1.0.0'
  ]
}
```

Why is there still no detailed instruction on what to do in this case? There was no answer on google.

### LINKED ISSUE #997: Can't build windows apps using docker
**Bug description**
nativefier is failing to build windows app.

**Steps to reproduce**
`docker build -t local/nativefier .`
`docker run --rm -v $(pwd):/target local/nativefier -p windows http://google.com /target/`

**Expected behavior**
Successful build

**Actual behavior**
Failed build

**Debug info**
```
Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform win32 x64 using electron v9.0.4
Error during build. Run with --verbose for details. Error: Could not find "wine64" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine64" executable is in your PATH.

See https://github.com/electron/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine64',
  path: 'wine64',
  spawnargs: [
    '/nativefier/node_modules/rcedit/bin/rcedit-x64.exe',
    '/target/Google-win32-x64/Google.exe',
    '--set-version-string',
    'FileDescription',
    [Function],
    '--set-version-string',
    'InternalName',
    [Function],
    '--set-version-string',
    'OriginalFilename',
    'Google.exe',
    '--set-version-string',
    'ProductName',
    [Function],
    '--set-version-string',
    'CompanyName',
    'Jia Hao',
    '--set-file-version',
    '1.0.0',
    '--set-product-version',
    '1.0.0',
    '--set-icon',
    '/tmp/nativefier-18-10-25-iconconv--1-P43AEb8JRRah/icon.ico'
  ]
}
```

**Context**
 - Nativefier: 9.0.0
 - OS: (arch linux)

### PR DESCRIPTION
**Pull request by TheCleric**
So like many things, this fix started simple, with me just wanting to fix the Docker Windows builds to fix #997.

However, tugging at that thread uncovered more threads, and here we are. I do have the pure Docker fix in its own commit which I could create a PR for separately if desired, but I figured I'd put all these related fixes in one PR. In fixing the Docker issue, I was able to convert over to Alpine (accomplishing the closed #890). ~~As part of testing this Docker issue, I wanted to make sure I could still build Windows (and all other platforms) with all supported architectures. In researching which platforms supported which archs in electron, I came across a nifty arch option: `all`. (https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#arch). Which led me to discover the equivalent platform option (https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#platform). And these seemed like a good way to ensure the Docker gets tested well.~~

So in this PR:
- Docker builds for Windows are fixed (fixes #997 )
- Switched over to use alpine (as was indicated as desired in https://github.com/nativefier/nativefier/issues/375#issuecomment-304247033) - which may mean #375 is likely fixed as well.
- Fixed bug where Docker has the wrong line endings when copying from a Windows host
- Fixed the invalid `arm` arch to `armv7l`
- Add `npm t` to the docker build to ensure tests pass before we start trying to do builds
- ~~Allow use of the electron packager "all" platform to build for all supported platforms~~
    - ~~NOTE: When specifying `all` for platform, and no user agent is specified, a generic chrome user agent will be calculated that omits OS and Arch~~
- ~~Allow use of the electron packager "all" arch to build for all supported archs~~
- Add a message to help the user when trying to build Mac apps on Windows as a non-Admin (currently an unhelpful exception)

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -1,34 +1,33 @@
-FROM node:12-stretch
-LABEL description="Debian image to build nativefier apps"
+FROM node:12-alpine
```
Comment (ronjouch) [inline Dockerfile:1]: Happy to switch to Alpine. In the past it used to have binary compatibility (because musl, I think?) trouble.

Did you test the final image under Windows and macOS/Linux? Do you confirm it runs fine?

File: Dockerfile [hunk 2]
```diff
@@ -1,34 +1,33 @@
...
-# Forced us to use Debian rather than Alpine, which doesn't do multiarch.
-RUN dpkg --add-architecture i386
 
 # Install dependencies
-RUN apt-get update \
-    && apt-get --yes install wine32 imagemagick \
-    && apt-get clean && rm -rf /var/lib/apt/lists/*
+RUN apk update \
+    && apk add bash wine imagemagick dos2unix \
+    && rm -rf /var/lib/apk/lists/*
```
Comment (ronjouch) [inline Dockerfile:8]: Hmmmmmmmm are you sure this is the path for `apk` cache? (I'm surprised it'd exactly at the same spot, except for t → k)

File: src/build/buildNativefierApp.ts [hunk 3]
```diff
@@ -1,15 +1,14 @@
-import * as path from 'path';
-
 import * as electronGet from '@electron/get';
 import * as electronPackager from 'electron-packager';
 import * as hasbin from 'hasbin';
 import * as log from 'loglevel';
-
-import { isWindows, getTempDir, copyFileOrDir } from '../helpers/helpers';
+import * as path from 'path';
```
Comment (ronjouch) [inline src/build/buildNativefierApp.ts:5]: Like elsewhere, please leave at the top, because it's a system dep

**Review by ronjouch — CHANGES_REQUESTED** [review]
Thanks @TheCleric ! I'm happy about:

- Docker stuff: build fixed under Windows, Alpine, line endings, npm t.
- The message to warn when trying a Mac build on Windows as a non-Admin (with a request to get rid of the extra dep).

... but I'm not convinced about the `all` thing. I wrote a few comments about it, but the most important of them is: why do you want this in the first place / is it really valuable? So far I don't see the value in it (the Docker build was fine with three repeated calls), and if you convince me there is, then it feels like more work is needed, that would belong to another PR to separate things.

File: Dockerfile [hunk 4]
```diff
@@ -1,34 +1,33 @@
...
+
+WORKDIR /nativefier
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply Dockerfile:10]: The `electron-packager` uses a package called `rcedit` to generate its packages. It appears that was updated to call wine64 instead of wine if its host os was 64 bit, so with us having wine32 hard coded in there, it was failing do to an inability to find wine64.

File: src/build/buildNativefierApp.ts [hunk 5]
```diff
@@ -123,9 +139,10 @@ export async function buildNativefierApp(
   const appPathArray = await electronPackager(options.packager);
 
   log.info('\nFinalizing build...');
-  const appPath = getAppPath(appPathArray);
+  const appPaths =
+    options.packager.arch === 'all' ? appPathArray : [getAppPath(appPathArray)];
 
-  if (appPath) {
+  if (appPaths) {
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/build/buildNativefierApp.ts:145]: Sorry, my python background snuck in there. :)

File: src/cli.ts [hunk 6]
```diff
@@ -1,13 +1,11 @@
 #!/usr/bin/env node
-import 'source-map-support/register';
-
 import * as commander from 'commander';
 import * as dns from 'dns';
 import * as log from 'loglevel';
-
+import 'source-map-support/register';
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/cli.ts:5]: Sorry, victim of an autoformat sort.

File: src/helpers/helpers.ts [hunk 7]
```diff
@@ -1,11 +1,11 @@
-import * as os from 'os';
-import * as path from 'path';
-
 import axios from 'axios';
 import * as hasbin from 'hasbin';
-import { ncp } from 'ncp';
 import * as log from 'loglevel';
+import { ncp } from 'ncp';
+import * as os from 'os';
+import * as path from 'path';
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/helpers/helpers.ts:6]: See above comment about autoformat. 😆 

Will fix.

File: src/build/buildNativefierApp.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (ronjouch) [reply src/build/buildNativefierApp.ts:145]: > Sorry, my python background snuck in there. :)

Hehe, I can relate 😄. Sadly, we'll never see an empty array being trueish, because backwards compatibility. But thankfully, new JS features are now better designed, with proper RFCing. Also, I WANT LIST/GENERATOR COMPREHENSIONS IN JAVASCRIPT.

File: Dockerfile (hunk 2 above)
Comment (TheCleric) [reply Dockerfile:8]: It is not. I thought in an example I was following that's what they had, but I may have gotten led astray. Will fix.

File: src/infer/inferUserAgent.ts [hunk 8]
```diff
@@ -59,6 +59,9 @@ export function getUserAgentString(
     case 'linux':
       userAgent = `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${chromeVersion} Safari/537.36`;
       break;
+    case 'all':
+      userAgent = `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${chromeVersion} Safari/537.36`;
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/infer/inferUserAgent.ts:63]: > Care to either do more refactor or abandon it?

Sure. I'm not married to it, so whatever's best for the project is fine by me.

> Also, in the first place, why do you need it?

It would seem useful to me if generating an app for downstream distribution, but I'll readily admit that this is not how I use Nativefier, nor do I know what the real world proportion of people who use it that way versus just to create a personal, one off app. As well for me it seemed like an easy win from the perspective of `electron-packager` supported it, so why not us? But perhaps that's the wrong way of looking at it and it's added complexity with no real world benefit for the majority of users. Would all depend on who Nativefier's actual user base is and what their use cases are (of which I readily admit I do not have a good awareness).

> I'll listen, but it seems like a feature that is both problematic and YAGNI anyway, so if it's just for the Docker build I'd like it removed.

The Docker build reason was only a small part of the overall reason, though that was convenient for ensuring that my changes did not break the app build. My main reasoning was that it seemed like a valuable thing to support from the perspective of giving the user a convenient way to build multiple platforms, though admittedly hand rolling a few commands joined by `&&` is not terribly onerous. So if we decide this use case is worth it, great. However, if we decide it's added complexity for very little real world benefit, I could see that too. As the current maintainer of the project, I would naturally follow what you think is best.

File: src/build/buildNativefierApp.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/build/buildNativefierApp.ts:145]: > I WANT LIST/GENERATOR COMPREHENSIONS IN JAVASCRIPT.

Amen.

File: src/infer/inferUserAgent.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/infer/inferUserAgent.ts:63]: Oh and:

> Why should all end up as AppleWebkit?

I just grabbed the first entry and removed the OS/Arch and didn't see that part. I'll drop that.

File: src/cli.ts [hunk 9]
```diff
@@ -102,8 +100,18 @@ if (require.main === module) {
       positionalOptions.out = outputDirectory;
     })
     .option('-n, --name <value>', 'app name')
-    .option('-p, --platform <value>', "'mac', 'mas', 'linux' or 'windows'")
-    .option('-a, --arch <value>', "'ia32' or 'x64' or 'arm' or 'arm64'")
+    // Current Electron Packager supported platform list:
+    // https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#platform
+    .addOption(
+      new commander.Option('-p, --platform <value>').choices(
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/cli.ts:106]:
```
  -p, --platform <value>                             (choices: "all", "linux", "mac", "mas", "windows")
  -a, --arch <value>                                 (choices: "all", "ia32", "x64", "armv7l", "arm64")
```

[the remark this answers is not in the document]
Comment (TheCleric) [reply src/cli.ts:106]: Also here's the sample output if you provide a bad option:
```
error: option '-a, --arch <value>' argument 'blah' is invalid. Allowed choices are all, ia32, x64, armv7l, arm64.
```

File: Dockerfile (hunk 1 above)
Comment (TheCleric) [reply Dockerfile:1]: I did test the final generated app under Windows and Mac. I could install VirtualBox and test under Linux if needed as well.

File: src/infer/inferUserAgent.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/infer/inferUserAgent.ts:63]: Although looking at it here are all the current ones:

```
  darwin: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${DEFAULT_CHROME_VERSION} Safari/537.36`,
  mas: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${DEFAULT_CHROME_VERSION} Safari/537.36`,
  win32: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${DEFAULT_CHROME_VERSION} Safari/537.36`,
  linux: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${DEFAULT_CHROME_VERSION} Safari/537.36`,
```

All have AppleWebKit, all have Safari. Not sure about either of those.

File: Dockerfile [hunk 10]
```diff
@@ -1,34 +1,33 @@
...
-# Run a {lin,mac,win} build: 1. to check installation was sucessful,
-# 2. to cache electron distributables and avoid downloads at runtime.
-RUN nativefier https://github.com/nativefier/nativefier /tmp/nativefier \
-    && nativefier -p osx https://github.com/nativefier/nativefier /tmp/nativefier \
-    && nativefier -p windows https://github.com/nativefier/nativefier /tmp/nativefier \
-    && rm -rf /tmp/nativefier
+# Run a build of all platforms and archs:
+# 1. to check installation was sucessful
+# 2. to cache electron distributables and avoid downloads at runtime
+RUN nativefier -p all -a all https://github.com/nativefier/nativefier /tmp/nativefier
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply Dockerfile:32]: So here's the file sizes, and timings:

. | Electron Cache Size in Docker | Generated App Folder Size in Docker (pre-deletion) | Final Size of / (after deleting the generated apps) | Time to build
-- | -- | -- | -- | --
Before | 221.9 MB | 948.4 MB | 1.1 GB | 3:46.91 |
After | 809.7 MB | 1.9 GB | 1.6 GB | 4:19.19 |

So overall it uses about 588 MB more space to cache the extra files.

As well I've added some echos in the Dockerfile to render these sizes so we can see this clearly.

File: src/cli.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (ronjouch) [reply src/cli.ts:109]: Neato. 👍!

File: src/helpers/helpers.ts [hunk 11]
```diff
@@ -95,6 +95,11 @@ export function getAllowedIconFormats(platform: string): string[] {
       case 'win32':
         formats.push('.ico');
         break;
+      case 'all':
+        formats.push('.icns');
+        formats.push('.png');
+        formats.push('.ico');
+        break;
```
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/helpers/helpers.ts:117]: It doesn't break the generation, but I will have to validate the app got the correct icon.

File: src/infer/inferUserAgent.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (ronjouch) [reply src/infer/inferUserAgent.ts:63]: @TheCleric thanks for the exhaustive follow-up and data about `all`. My updated thoughts:

1. The seriously increased Docker size you [measure in your other post](https://github.com/nativefier/nativefier/pull/1122#discussion_r584944697) for niche use case is definitely a concern. A user doing a ton of builds for all platforms would have benefited from your `all` code, but this user is hypothetical to me until I've heard about them, and even then they would remain marginal, and not worth the high bandwidth cost demanded to all users (remember not everybody has a good internet connection).
2. *"That was convenient for ensuring that my changes did not break the app build"*: okay I understand, but doing so in the final for-users Dockerfile doesn't feel like the right place to do so. We can always do with more integration tests, but they should belong to integration tests, not to the final paid-by-users Docker image.
3. On the need for `all`:
    1. As you wrote, a few `&&` chains do the job well
    2. If (and that's a real if) we want something better, maybe we should instead have some kind of `arch1,arch2,arch3` syntax, rather than `all`, whose sole users would be us in a CI job, increasing complexity and command-line API bloat for our sole needs? And even then, not convinced of the benefits of `arch1,arch2,arch3` vs a few `&&`s.
4. You might have twitched on me writing "increasing complexity" above, as this isn't rocket science, and given the quality of what you're pushing, I'm certain you'd easily iron out the bugs (useragent, icon) I pointed with a refactor. My sensitivity here is that for now, Nativefier is in super-minimal maintenance mode (see my blah at the top of README.md), so I'm extremely picky and ruthless about what gets in: anything not a bugfix or not clearly valuable I'd rather leave out.
    - On that, by the way, my message in README is a double-edged sword: I'm encouraging contributions, but on the other side I'm clearly not an "accept all" maintainer. :shrug: , I may try a rephrase but it's difficult, I definitely don't want to discourage, but sometimes submitters get frustrated that I heavily bend their PRs, or alright reject them. More often than not, though, they seem to understand, and things go well, like I think is happening here. I welcome your feedback about it.

So, thanks for mentioning you're not super attached to this feature and would agree to remove it. Given this discussion, yup I confirm I'd like to see it removed from the PR.

File: Dockerfile (hunk 10 above)
[the remark this answers is not in the document]
Comment (ronjouch) [reply Dockerfile:35]: Thaaaaaaaaaaanks for the data. Replying in https://github.com/nativefier/nativefier/pull/1122#discussion_r584965481 .

File: src/infer/inferUserAgent.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (TheCleric) [reply src/infer/inferUserAgent.ts:63]: > so I'm extremely picky and ruthless about what gets in: anything not a bugfix or not clearly valuable I'd rather leave out.

To be clear, I thought you were fair in this PR and I was not frustrated about this at all. Having done my share of open source contributions, I've learned by now that what my idea of a good idea may not necessarily fit with what is good for the overall project. You gave me a chance to justify my reasoning, and in balance of risk vs. reward, you made a decision that you think is best for the project (and I can't say you're wrong). If I was super worried about not throwing this code away I would have created an issue first and talked it over. So no big deal. I'll get it removed. 😄

**Comment by TheCleric** [comment]
@ronjouch I have removed the `all` code. Testing the Linux apps generated under the Dockerfile and verifying the is-admin changes on my Windows box. Please hold off on merging until I can verify both.

File: src/helpers/helpers.ts [hunk 12]
```diff
@@ -24,6 +26,14 @@ export function isWindows(): boolean {
   return os.platform() === 'win32';
 }
 
+export function isWindowsAdmin(): boolean {
+  if (process.platform !== 'win32') {
+    return false;
+  }
+
+  return spawnSync('fltmc').status === 0;
```
Comment (ronjouch) [inline src/helpers/helpers.ts:34]:
```suggestion
  // https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights
  // https://stackoverflow.com/questions/57009374/check-admin-or-non-admin-users-in-nodejs-or-javascript
  return spawnSync('fltmc').status === 0;
```

File: Dockerfile [hunk 13]
```diff
@@ -1,34 +1,47 @@
...
 RUN nativefier https://github.com/nativefier/nativefier /tmp/nativefier \
     && nativefier -p osx https://github.com/nativefier/nativefier /tmp/nativefier \
-    && nativefier -p windows https://github.com/nativefier/nativefier /tmp/nativefier \
-    && rm -rf /tmp/nativefier
+    && nativefier -p windows https://github.com/nativefier/nativefier /tmp/nativefier
+
+
+RUN echo Generated total cache size: $(du -sh ~/.cache/electron) \
+    && echo Generated total app size: $(du -sh /tmp/nativefier) \
+    && rm -rf /tmp/nativefier \
```
Comment (ronjouch) [inline Dockerfile:43]: I'd remove this log, since we're removing `/tmp/nativefier` anyway, it's not of importance to end users.

```suggestion
    && rm -rf /tmp/nativefier \
```

File: Dockerfile [hunk 14]
```diff
@@ -1,34 +1,47 @@
...
+# 1. to check installation was sucessful
+# 2. to cache electron distributables and avoid downloads at runtime
 RUN nativefier https://github.com/nativefier/nativefier /tmp/nativefier \
     && nativefier -p osx https://github.com/nativefier/nativefier /tmp/nativefier \
-    && nativefier -p windows https://github.com/nativefier/nativefier /tmp/nativefier \
-    && rm -rf /tmp/nativefier
+    && nativefier -p windows https://github.com/nativefier/nativefier /tmp/nativefier
+
+
+RUN echo Generated total cache size: $(du -sh ~/.cache/electron) \
```
Comment (ronjouch) [inline Dockerfile:41]:
```suggestion
RUN echo Generated Electron cache size: $(du -sh ~/.cache/electron) \
```

File: Dockerfile [hunk 15]
```diff
@@ -1,34 +1,47 @@
...
 
 # Build nativefier and link globally
 WORKDIR /nativefier/app
 RUN npm install
 WORKDIR /nativefier
-RUN npm install && npm run build && npm link
+
+# Install (which will also install in ./app, and build, thanks to our `prepare` npm hook)
+# Also, running tests, to ensure we don't Docker build & publish broken stuff
+RUN npm install && npm run build && npm test && npm link
```
Comment (ronjouch) [inline Dockerfile:25]: **Last remaining question**: In an earlier comment I was suggesting that `npm run build` is unnecessary, since already run through `prepare` after `install`. Was I wrong, or did my message get lost during the review? If not,

```suggestion
RUN npm install && npm test && npm link
```

**Review by ronjouch — COMMENTED** [review]
Wheeee. I have a couple of comment/doc nits that I'll apply & resolve directly, and one actual remaining question:

File: Dockerfile (hunk 15 above)
Comment (TheCleric) [reply Dockerfile:25]: It did not get lost. I apologize for not communicating, but the npm install inside the docker image did not seem to execute the prepare:

```#13 [ 9/12] RUN npm install && npm test && npm link
#13 13.86 npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
#13 22.44 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#13 22.45 npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
#13 25.06 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#13 27.94 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#13 27.98 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#13 60.33
#13 60.33 > core-js@3.9.1 postinstall /nativefier/node_modules/core-js
#13 60.33 > node -e "try{require('./postinstall')}catch(e){}"
#13 60.33
#13 60.46 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
#13 60.46
#13 60.46 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
#13 60.46 > https://opencollective.com/core-js
#13 60.46 > https://www.patreon.com/zloirock
#13 60.46
#13 60.46 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
#13 60.46
#13 61.65 npm WARN lifecycle nativefier@42.3.0~prepare: cannot run in wd nativefier@42.3.0 cd app && npm install && cd .. && npm run build (wd=/nativefier)
#13 62.53 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
#13 62.53 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#13 62.53
#13 62.57 added 858 packages from 522 contributors and audited 861 packages in 60.667s
#13 63.63
#13 63.63 76 packages are looking for funding
#13 63.63   run `npm fund` for details
#13 63.63
#13 63.63 found 0 vulnerabilities
#13 63.63
#13 64.17
#13 64.17 > nativefier@42.3.0 test /nativefier
#13 64.17 > jest --testRegex '[-.]test\.js$'
#13 64.17
#13 64.63 ● Validation Error:
#13 64.63
#13 64.63   Module ./lib/jestSetupFiles in the setupFiles option was not found.
#13 64.63          <rootDir> is: /nativefier
#13 64.63
#13 64.63   Configuration Documentation:
#13 64.63   https://jestjs.io/docs/configuration.html
#13 64.63
#13 64.64 npm ERR! Test failed.  See above for more details.
#13 ERROR: executor failed running [/bin/sh -c npm install && npm test && npm link]: exit code: 1
------
 > [ 9/12] RUN npm install && npm test && npm link:
------
executor failed running [/bin/sh -c npm install && npm test && npm link]: exit code: 1
```

Comment (TheCleric) [reply Dockerfile:25]: Digging in a little bit, it appears that for safety, `prepare` won't run as root:

https://github.com/npm/npm/issues/17346

Comment (ronjouch) [reply Dockerfile:25]: > Digging in a little bit, it appears that for safety, `prepare` won't run as root: [npm/npm#17346](https://github.com/npm/npm/issues/17346)

@TheCleric ooooh, okay, nice find. Adding a lil' comment to document it's necessary, and a link to the npm issue.

Comment (TheCleric) [reply Dockerfile:25]: I'm seeing if I have a workaround if you want, or we can merge it as is.

Comment (TheCleric) [reply Dockerfile:25]: Nope, didn't work. 😆

Comment (ronjouch) [reply Dockerfile:25]: Nah it's all good.

But wait, how does thing even work, then?! (No, I'm not super familiar with our Docker build 😄). If `prepare` doesn't run on `install`, it means that the `cd app && npm install && cd ..` bit of `prepare` doesn't run either, so the app will generate, but will be broken at runtime as missing dependencies (for the app, not the build time CLI builder). If it used to be the case, Docker users (and I know we have a few) would have complained about it, so I understand that the build behaved differently before your PR? However, that doesn't make sense, the position of the `USER` statement before the npm install didn't budge with your PR, so we should have been making broken Docker builds before your PR.

I don't understand what's going on. Do you? Do the app generated by Docker work?

Comment (TheCleric) [reply Dockerfile:25]: They work because we're manually doing those steps:

```
# Build nativefier and link globally
WORKDIR /nativefier/app
RUN npm install
```

Comment (ronjouch) [reply Dockerfile:25]: Aaaaaaaaaalright, makes sense, had missed those.

File: Dockerfile [hunk 16]
```diff
@@ -1,34 +1,46 @@
...
+# Fix line endings that may have gotten mangled in Windows
+RUN find ./icon-scripts ./src ./app -type f -print0 | xargs -0 dos2unix
 
 # Build nativefier and link globally
 WORKDIR /nativefier/app
 RUN npm install
 WORKDIR /nativefier
-RUN npm install && npm run build && npm link
+
+# Install (which will also install in ./app, and build, thanks to our `prepare` npm hook)
```
Comment (ronjouch) [inline Dockerfile:23]:
```suggestion
# Install (note that we had to manually install in `app` before, as `prepare` won't run as root)
```

**Review by ronjouch — APPROVED** [review]

**Comment by ronjouch** [comment]
yay

@TheCleric merging. Great work, thanks!

**Comment by TheCleric** [comment]
> @TheCleric merging. Great work, thanks!

You're welcome. Thanks for helping me get it through.

**Comment by ronjouch** [comment]
I'll cut a release soon-ish.

**Comment by ronjouch** [comment]
Released in v42.4.0. Thanks!

File: Dockerfile [hunk 17]
```diff
@@ -1,34 +1,46 @@
...
 RUN npm install
 WORKDIR /nativefier
-RUN npm install && npm run build && npm link
+
+# Install (note that we had to manually install in `app` before, as `prepare` won't run as root)
+# Also, running tests, to ensure we don't Docker build & publish broken stuff
+RUN npm install && npm run build && npm test && npm link
+
+# Cleanup test artifacts
+RUN rm -rf /tmp/nativefier*
```
Comment (SuperSandro2000) [inline Dockerfile:28]: This does not work because the files are already cached in the layers and the size won't be reduced.

Comment (TheCleric) [reply Dockerfile:28]: Good point! I'll combine this (and a similar one) into the same step they're generated in so they never get cached to a layer.

Comment (TheCleric) [reply Dockerfile:28]: I think I have a fix in #1128, could you take a look @SuperSandro2000? Thanks!
